Repository openshift/cluster-csi-snapshot-controller-operator, pull requests merged in 2020-10, with the labels that each got.

#49 Bug 1879365: Remove namespace creation
  manifests/00_namespace.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#59 Add BZ component to OWNERS
  OWNERS
Labels: approved, lgtm

#57 Bug 1839239: Update version only after having rolled out the new operand
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#60 Change to "component" for BZ component
  OWNERS
Labels: approved, lgtm

#61 add current profile annotations to CVO manifests
  manifests/02_operator_cr.yaml
  manifests/03_configmap.yaml
  manifests/03_service.yaml
  manifests/04_serviceaccount.yaml
  manifests/05_operand_rbac.yaml
  manifests/05_operator_rbac.yaml
  manifests/05_user_rbac.yaml
  manifests/07_deployment.yaml
  manifests/08_clusteroperator.yaml
Labels: approved, lgtm
