Repository openshift/cluster-csi-snapshot-controller-operator, pull requests merged in 2020-12, with the labels that each got.

#62 Add validation webhook deployment
  assets/webhook_deployment.yaml
  manifests/07_deployment.yaml
  manifests/08_webhook_service.yaml
  manifests/09_webhook_config.yaml
  manifests/10_clusteroperator.yaml
  manifests/image-references
  pkg/generated/bindata.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/starter.go
  pkg/operator/webhookdeployment/webhook.go
  pkg/operator/webhookdeployment/webhook_test.go
  pkg/operatorclient/operatorclient.go
Labels: approved, lgtm

#67 Bug 1905320: Add memory limit for webhook container.
  assets/webhook_deployment.yaml
  manifests/07_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#69 Bug 1906518: Update Snapshot CRDs to v1
  assets/volumesnapshotclasses.yaml
  assets/volumesnapshotcontents.yaml
  assets/volumesnapshots.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#70 Bug 1908349: Don't validate v1 objects
  manifests/09_webhook_config.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
