Repository openshift/cluster-csi-snapshot-controller-operator, pull requests merged in 2020-02, with the labels that each got.

#26 Bug 1797694: Remove unused variable and file
  pkg/operator/operator.go
  pkg/operator/version.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#28 Bug 1798448: Use Origin images from quay.io/openshift
  manifests/07_deployment.yaml
  manifests/image-references
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#30 Bug 1800437, Bug 1800470, Bug 1800477: Update getters to match upstream
  assets/volumesnapshotclasses.yaml
  assets/volumesnapshotcontents.yaml
  assets/volumesnapshots.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/valid-bug, kind/bug, lgtm, size/L
