Repository openshift/cluster-csi-snapshot-controller-operator, pull requests merged in 2021-06, with the labels that each got.

#76 'manages'
  README.md
Labels: approved, lgtm, lifecycle/rotten, ok-to-test

#90 readme: update references to developer guide
  README.md
Labels: approved, lgtm

#93 Bug 1965263: VolumeSnapshotContents listing should print also namespace of the VolumeSnapshot ref.
  assets/volumesnapshotcontents.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
