Repository openshift/cluster-csi-snapshot-controller-operator, pull requests merged in 2023-09, with the labels that each got.

#159 OCPBUGS-3680: Move readonlyRootFilesystem to the right place
  manifests/07_deployment-hypershift.yaml
  manifests/07_deployment-ibm-cloud-managed.yaml
  manifests/07_deployment.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#157 STOR-1443: Restart webhook Pods if `csi-snapshot-webhook-secret` changed
  manifests/05_operator_role-hypershift.yaml
  manifests/05_operator_role.yaml
  pkg/operator/starter.go
Labels: lgtm, approved, docs-approved, px-approved, qe-approved, jira/valid-reference

#162 OCPBUGS-18801: Move readonlyRootFilesystem to the right place - 4.14
  manifests/07_deployment-hypershift.yaml
  manifests/07_deployment-ibm-cloud-managed.yaml
  manifests/07_deployment.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
