Repository openshift/cluster-csi-snapshot-controller-operator, pull requests merged in 2024-04, with the labels that each got.

#202 OCPBUGS-31497: create suitable role and roleBinding for csi-snapshot-webhook
  assets/rbac/csi_snapshot_controller_clusterrole.yaml
  assets/rbac/csi_snapshot_controller_clusterrolebinding.yaml
  assets/rbac/webhook_clusterrole.yaml
  assets/webhook_config.yaml
  manifests/05_operand_rbac.yaml
  manifests/05_operator_clusterrole.yaml
  pkg/operator/starter.go
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#203 [4.15] OCPBUGS-31599: create suitable role and roleBinding for csi-snapshot-webhook
  assets/assets.go
  assets/rbac/webhook_clusterrole.yaml
  assets/rbac/webhook_clusterrolebinding.yaml
  assets/webhook_deployment.yaml
  assets/webhook_serviceaccount.yaml
  manifests/05_operator_clusterrole.yaml
  pkg/operator/starter.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#201 STOR-1573: Update manifests to v7.0.0
  assets/volumesnapshotclasses.yaml
  assets/volumesnapshotcontents.yaml
  assets/volumesnapshots.yaml
Labels: lgtm, approved, docs-approved, px-approved, qe-approved, jira/valid-reference

#193 OCPBUGS-28230: add FallbackToLogsOnError for easier debugging
  assets/csi_controller_deployment.yaml
  assets/webhook_deployment.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
